# -*- coding: utf-8 -*-
"""area_of _the _circle_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-6DLkh1gIkJxQJdm6oywDVInUVJI-eF
"""

radius = float(input("Enter the radius of the circle: "))
area = 3.14159265359*radius*radius #Using the accurate pi value to get accurate answer.
print("The area of the circle with radius "+str(radius)+" is " +str(area))