# -*- coding: utf-8 -*-
"""filename_extension_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BN_KVmtEcBNs1Dhm_4z9U4CkU469Goin
"""

filename=input("Enter the filename:")
extension=filename.split(".")
if extension[-1]=="py":
  print("The file extension of the file is python")
else:
  print("The file extension of the file is "+extension[-1])