# -*- coding: utf-8 -*-
"""most_frequent_char_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17z-Qmu3EJs3XY_6vBRSkHZNGinQJVB8d
"""

string=input("Enter a String:")  # taking the input 

def most_frequent(string):     #creating the function with inputted string as the argument
  dict={}                      #creating empty dictionary
  for n in string:
    keys= dict.keys() # We assign the keys to the char of the string 
    if n in dict:     # Checking whether the char is present in the dictionary or not and if present we increment the count else keep it 1
      dict[n]+= 1
    else:
      dict[n]=1
  return dict
print(most_frequent(string))