# -*- coding: utf-8 -*-
"""positive_numbers_in_list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rtXL5w5OdsBsMI1nE9GBoK84KLxRvBNM
"""

l_range=int(input("Enter the no. of elements in list:"))

list=[]
for i in range(l_range):
  x=int(input())
  list.append(x)
print("List:",list)

for i in list:
  if i<0:
    list.remove(i)

print("List without negative element is:" ,list)