# -*- coding: utf-8 -*-
"""wikipedia_footer_webscrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uf6xPbBr5Ds6e0ruWm-69cdnMni6CSqT
"""

import requests
from bs4 import BeautifulSoup

wiki_url="https://www.wikipedia.org/"

req=requests.get(wiki_url)
content=req.content

soup= BeautifulSoup(content,"html.parser")
wiki_footer_data = soup.find_all("div",{"class":"other-project"})

for footer in wiki_footer_data:
  footer_project=footer.find("div",{"class":"other-project-text"}).text
  print(footer_project)